export const LOAD_ITEM_SUCCESS = 'LOAD_ITEM_SUCCESS';  
export const FITER_FAILURE = 'FITER_FAILURE';
export const FILTER_SUCCESS = 'FILTER_SUCCESS';  
export const LOADING = 'LOADING';
export const LOAD_ITEM_BODY_SUCCESS = 'LOAD_ITEM_BODY_SUCCESS';
export const LOAD_ITEM_BODY_FAILURE = 'LOAD_ITEM_BODY_FAILURE';